services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/app_development

  front:
    build: ./front
    volumes:
      - ./front:/app
    ports:
      - "5173:5173"
    depends_on:
      - api
    tty: true

volumes:
  postgres_data: